/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectIndexImport } from './routes/project/index'
import { Route as ProjectProjectImport } from './routes/project/$project'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectIndexRoute = ProjectIndexImport.update({
  path: '/project/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectRoute = ProjectProjectImport.update({
  path: '/project/$project',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/project/$project': {
      id: '/project/$project'
      path: '/project/$project'
      fullPath: '/project/$project'
      preLoaderRoute: typeof ProjectProjectImport
      parentRoute: typeof rootRoute
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProjectProjectRoute,
  ProjectIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/project/$project",
        "/project/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/project/$project": {
      "filePath": "project/$project.tsx"
    },
    "/project/": {
      "filePath": "project/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
